# Generated by Django 4.2.5 on 2023-09-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('directory_url', models.CharField(max_length=255)),
                ('industry_niche', models.CharField(max_length=100)),
                ('social_media_links', models.JSONField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('logo', models.FileField(upload_to='logos/')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
